import { Geist, Geist_Mono } from "next/font/google";
import I18nProvider from "../../components/I18nProvider.jsx";
import SidebarLayout from "../../components/SidebarLayout.jsx";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Samanyay AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <I18nProvider>
          <SidebarLayout>
            {children}
          </SidebarLayout>
        </I18nProvider>
      </body>
    </html>
  );
}
