import { Geist, Geist_Mono } from "next/font/google";
import I18nProvider from "../../components/I18nProvider.jsx";
import NavbarProvider from "../../components/NavbarContext.jsx";
import { UserProvider } from "../../components/UserContext.jsx";
import SidebarLayout from "../../components/SidebarLayout.jsx";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Samanyay AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Devanagari:wght@400;500;600;700&family=Noto+Sans+Gujarati:wght@400;500;600;700&display=swap" rel="stylesheet" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <UserProvider>
          <I18nProvider>
            <NavbarProvider>
              <SidebarLayout>
                {children}
              </SidebarLayout>
            </NavbarProvider>
          </I18nProvider>
        </UserProvider>
      </body>
    </html>
  );
}
